### ISSUE TITLE
  giftless.local.yaml configuration - error 

### ISSUE THREAD

**Issue by mariorodeghiero** [datopian/giftless#9]
I tried to follow this [configuration](https://github.com/datopian/giftless#configuration) but didn't work properly. I received an error **"Object does not exist"**

**giftless.loca.yaml file**
```
AUTH_PROVIDERS: 
  - "giftless.auth.allow_anon:read_write"

TRANSFER_ADAPTERS:
  basic:
    factory: giftless.transfer.basic_external:factory
    options:
      storage_class: ..storage.azure:AzureBlobsStorage
      storage_options:
        connection_string: key
        container_name: lfs-storage
        path_prefix: lfs
```

**Post:**
```
{
    "operation": "upload",
    "transfers": [ "basic" ],
    "ref": { "name": "refs/heads/contrib" },
    "objects": [
      {
	"oid": "8857053d874453bbe8e7613b09874e2d8fc9ddffd2130a579ca918301c31b369",
        "size": 36
      }
    ]
 }
```

**console error:**

```
Traceback (most recent call last):
  File "/home/rodeghiero/datopian/giftless-new/.venv/lib/python3.6/site-packages/flask/app.py", line 2463, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/rodeghiero/datopian/giftless-new/.venv/lib/python3.6/site-packages/flask/app.py", line 2449, in wsgi_app
    response = self.handle_exception(e)
  File "/home/rodeghiero/datopian/giftless-new/.venv/lib/python3.6/site-packages/flask/app.py", line 1866, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/rodeghiero/datopian/giftless-new/.venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/rodeghiero/datopian/giftless-new/.venv/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/rodeghiero/datopian/giftless-new/.venv/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_requ
est
    rv = self.handle_user_exception(e)
  File "/home/rodeghiero/datopian/giftless-new/.venv/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_except
ion
    reraise(exc_type, exc_value, tb)
  File "/home/rodeghiero/datopian/giftless-new/.venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/rodeghiero/datopian/giftless-new/.venv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/rodeghiero/datopian/giftless-new/.venv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/rodeghiero/datopian/giftless-new/.venv/lib/python3.6/site-packages/flask_classful.py", line 301, in proxy
    response = view(**request.view_args)
  File "/home/rodeghiero/datopian/giftless-new/giftless/auth/__init__.py", line 78, in decorated_function
    return f(*args, **kwargs)
  File "/home/rodeghiero/datopian/giftless-new/.venv/lib/python3.6/site-packages/flask_classful.py", line 269, in inner
    return fn(*args, **kwargs)
  File "/home/rodeghiero/datopian/giftless-new/giftless/view.py", line 59, in post
    response['objects'] = [action(**o) for o in payload['objects']]
  File "/home/rodeghiero/datopian/giftless-new/giftless/view.py", line 59, in <listcomp>
    response['objects'] = [action(**o) for o in payload['objects']]
  File "/home/rodeghiero/datopian/giftless-new/giftless/transfer/basic_external.py", line 58, in upload
    if self.storage.verify_object(prefix, oid, size):
  File "/home/rodeghiero/datopian/giftless-new/giftless/transfer/basic_streaming.py", line 54, in verify_object
    return self.exists(prefix, oid) and self.get_size(prefix, oid) == size
  File "/home/rodeghiero/datopian/giftless-new/giftless/transfer/storage/azure.py", line 37, in exists
    self.get_size(prefix, oid)
  File "/home/rodeghiero/datopian/giftless-new/giftless/transfer/storage/azure.py", line 49, in get_size
    raise ObjectNotFound("Object does not exist")
giftless.transfer.exc.ObjectNotFound: Object does not exist
127.0.0.1 - - [08/Apr/2020 10:32:06] "GET /myorg/myrepo/objects/batch?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
127.0.0.1 - - [08/Apr/2020 10:32:06] "GET /myorg/myrepo/objects/batch?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
127.0.0.1 - - [08/Apr/2020 10:32:06] "GET /myorg/myrepo/objects/batch?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
127.0.0.1 - - [08/Apr/2020 10:32:06] "GET /myorg/myrepo/objects/batch?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200
```

**Comment by shevron** [comment]
Bug in Azure storage adapter confirmed and now fixed, please test again

**Comment by mariorodeghiero** [comment]
It works well now!
Thanks
